# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: TerraformDeployDev
  displayName: 'Terraform Deployment Dev'

  variables: 
    - group: dev-tf-vars 
  jobs:
  - job: DeployDev
    displayName: 'Terraform deploy Dev'

    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform 0.15.0'
      inputs:
        terraformVersion: '0.15.0'
    - task: TerraformTaskV2@2
      displayName: 'Terraform Init Dev'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'shuchita-payg'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'storagetfstatetest'
        backendAzureRmContainerName: 'tfstatecontainer'
        backendAzureRmKey: '$(environment).terraform.tfstate'
        workingDirectory: $(System.DefaultWorkingDirectory)/environment/dev
    - task: TerraformTaskV2@2
      displayName: 'Terraform Plan Dev'

      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'shuchita-payg'
        workingDirectory: $(System.DefaultWorkingDirectory)/environment/dev

    - task: TerraformTaskV2@2
      displayName: 'Terraform Apply Dev'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'shuchita-payg'
        workingDirectory: $(System.DefaultWorkingDirectory)/environment/dev
  
- stage: TerraformDeployTest
  displayName: 'Terraform Deployment Test'

  variables:
    - group: test-tf-vars
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation  
    pool: server    
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
          notifyUsers: |
              taneja_shuchita@hotmail.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'
  
  - job: ApplyTF
    displayName: 'Terraform Deploy Test'

    steps:
    - task: TerraformTaskV2@2
      displayName: 'Terraform Init Test'

      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'shuchita-payg'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'storagetfstatetest'
        backendAzureRmContainerName: 'tfstatecontainer'
        backendAzureRmKey: '$(environment).terraform.tfstate'
        workingDirectory: $(System.DefaultWorkingDirectory)/environment/test


    - task: TerraformCLI@0
      inputs:
        command: 'apply'
        environmentServiceName: 'shuchita-payg'
        workingDirectory: $(System.DefaultWorkingDirectory)/environment/test
        commandOptions: -var environment=$(environment)

